[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.5"
rand = "0.9.0"
rand_distr = "0.5.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "graph_info"
path = "src/bin/graph_info.rs"

[[bin]]
name = "graph_roundtrip"
path = "src/bin/graph_roundtrip.rs"

[[bench]]
name = "euclidean_distance"
harness = false
